spring:
  application:
    name: reactive-service-b
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/reactive_apps?locale=en_US
    username: root
    password: admin
    pool:
      max-size: 20
      validation-query: SELECT

server:
  port: 9091
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: simple
  cloudfoundry:
    skip-ssl-validation: true

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
