spring:
  application:
    name: reactive-service-b
  data:
    r2dbc:
      repositories:
        enabled: true
#    mongodb:
#      uri: mongodb://localhost:27017/reactive_app
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_app
    username: postgres
    password: postgres
    pool:
      max-size: 20
      validation-query: SELECT

server:
  port: 9091
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
