services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_DATABASE=mongo_product'
      - 'MONGO_INITDB_ROOT_USERNAME=mongo'
      - 'MONGO_INITDB_ROOT_PASSWORD=mongo'
