spring:
  application:
    name: reactive-service-a
  data:
    r2dbc:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://localhost:27017/reactive_app

server:
  port: 9092
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
